version: "3.9"

services:
  db:
    container_name: POSTGRESQL
    image: postgres:latest
    environment:
      POSTGRES_USER: "thortfull"
      POSTGRES_PASSWORD: "thortfull"
      POSTGRES_DB: "thortfull"
    ports:
      - "5432:5432"
    expose:
      - 5432
    healthcheck:
      test: [ "CMD-SHELL", "pg_isready -U thortfull" ]
      interval: 10s
      timeout: 5s
      retries: 5
    volumes:
      - ./postgres-data:/var/lib/postgresql/data  # Volume for persistent data
  app:
    build: .
    command: mvn install
    links:
      - db
    depends_on:
      - db
    ports:
      - "8090:8090"
    tty: true
    expose:
      - 8090
      - 9001
    environment:
      SPRING_DATASOURCE_URL: "jdbc:postgresql://localhost:5432/thortfull"
      SPRING_DATASOURCE_USERNAME: "thortfull"
      SPRING_DATASOURCE_PASSWORD: "thortfull"
    deploy:
      mode: replicated
      replicas: 1
      placement:
        constraints:
          - node.labels.type == app
      restart_policy:
        condition: on-failure
    healthcheck:
      test: "curl --fail --silent localhost:9001/actuator/health | grep UP || exit 1"
      interval: 20s
      timeout: 5s
      retries: 5
      start_period: 40s
    volumes:
      - ./api:/var/lib/data  # Volume for persistent data



